# Generated by Django 3.1.7 on 2021-03-26 16:44

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AntypicalChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_no', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('cdoc', models.FileField(blank=True, max_length=500, null=True, upload_to=api.models.AntypicalChild.cdoc_path)),
                ('cdoc_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dgform', models.FileField(blank=True, max_length=500, null=True, upload_to=api.models.AntypicalChild.dgform_path)),
                ('dgform_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CameraAngles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cameras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('resolution', models.CharField(blank=True, max_length=100, null=True)),
                ('megapixels', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypicalChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_no', models.CharField(max_length=20)),
                ('sequence_no', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('cdoc', models.FileField(blank=True, max_length=500, null=True, upload_to=api.models.TypicalChild.cdoc_path)),
                ('cdoc_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dgform', models.FileField(blank=True, max_length=500, null=True, upload_to=api.models.TypicalChild.dgform_path)),
                ('dgform_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to=api.models.Videos.video_upload_path)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('camera_name', models.CharField(blank=True, max_length=200, null=True)),
                ('camera_angle', models.CharField(blank=True, max_length=200, null=True)),
                ('camera_angle_name', models.CharField(blank=True, max_length=200, null=True)),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('file_extension', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('atChild', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='api.antypicalchild')),
                ('camera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='api.cameras')),
                ('session', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='api.sessions')),
                ('tChild', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='api.typicalchild')),
            ],
        ),
        migrations.CreateModel(
            name='VideoClips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('video', models.FileField(blank=True, null=True, upload_to='video_clips')),
                ('duration', models.DurationField(blank=True, null=True)),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_clips', to='api.videos')),
            ],
        ),
        migrations.AddField(
            model_name='sessions',
            name='atChild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='at_sessions', to='api.typicalchild'),
        ),
        migrations.AddField(
            model_name='sessions',
            name='tChild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_sessions', to='api.typicalchild'),
        ),
        migrations.AddField(
            model_name='sessions',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
