# Generated by Django 3.1.7 on 2021-03-13 11:14

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='filetype',
            new_name='file_type',
        ),
        migrations.AddField(
            model_name='videos',
            name='file_extension',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='consent_doc',
            field=models.FileField(blank=True, null=True, upload_to=api.models.Profiles.consent_doc_path),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=api.models.Videos.video_upload_path),
        ),
    ]
