# Generated by Django 3.1.7 on 2021-03-13 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210313_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='uploaded_datetime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='videos',
            name='last_modified_datetime',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='videos',
            name='uploaded_datetime',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
