# Generated by Django 3.1.7 on 2021-03-13 12:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210313_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessions',
            name='uploaded_datetime',
        ),
        migrations.AddField(
            model_name='sessions',
            name='created_datetime',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
