# Generated by Django 3.1.7 on 2021-03-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210313_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='last_modified_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='uploaded_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
