// child types
export const CHILD_TYPES = {
    TYPICAL: 'TYPICAL',
    ANTYPICAL: 'ANTYPICAL'
}

// play modes
export const PLAY_MODES = {
    SINGLE: 'SINGLE',
    ALL: 'ALL'
}

// play status
export const PLAY_STATUS = {
    PLAY: 'PLAY',
    PAUSE: 'PAUSE',
    STOP: 'STOP'
}

// localstorage value keys
export const CSAAT_VIDEO_UPLOAD_CHILDTYPE = 'CSAAT_VIDEO_UPLOAD_CHILDTYPE'
export const CSAAT_VIDEO_UPLOAD_ACTIVE_CHILD = 'CSAAT_VIDEO_UPLOAD_ACTIVE_CHILD'
export const CSAAT_VIDEO_UPLOAD_ACTIVE_CHILD_NAME = 'CSAAT_VIDEO_UPLOAD_ACTIVE_CHILD_NAME'
export const CSAAT_VIDEO_UPLOAD_ACTIVE_SESSION = 'CSAAT_VIDEO_UPLOAD_ACTIVE_SESSION'
export const CSAAT_VIDEO_UPLOAD_ACTIVE_NAV = 'CSAAT_VIDEO_UPLOAD_ACTIVE_NAV'

// children
export const FETCH_CHILDREN = 'FETCH_T_CHILDREN';
export const ADD_CHILD = 'ADD_T_CHILD';
export const UPDATE_CHILD = 'UPDATE_T_CHILD';
export const DELETE_CHILD = 'DELETE_T_CHILD';
export const DELETE_CHILDREN = 'DELETE_CHILDREN';

// sessions
export const FETCH_SESSIONS = 'FETCH_SESSIONS';
export const ADD_SESSION = 'ADD_SESSION';
export const UPDATE_SESSION = 'UPDATE_SESSION';
export const DELETE_SESSION = 'DELETE_SESSION';
export const DELETE_SESSIONS = 'DELETE_SESSIONS';
export const SET_ACTIVE_SESSION = 'SET_ACTIVE_SESSION';
export const SET_ACTIVE_SESSION_FIRST = 'SET_ACTIVE_SESSION';
export const UPDATE_ACTIVE_SESSION = 'UPDATE_ACTIVE_SESSION';



// videos
export const FETCH_VIDEOS = 'FETCH_VIDEOS';
export const ADD_VIDEO = 'ADD_VIDEO';
export const DELETE_VIDEO = 'DELETE_VIDEO';
export const DELETE_VIDEOS = 'DELETE_VIDEOS';

// audio
export const FETCH_AUDIO = 'FETCH_AUDIO';
export const ADD_AUDIO = 'ADD_AUDIO';
export const DELETE_AUDIO = 'DELETE_AUDIO';

// video play controls
export const TOOGLE_PLAY_MODE = 'TOOGLE_PLAY_MODE';
export const TOOGLE_PLAY_STATE = 'TOOGLE_PLAY_STATE';

// camera
export const FETCH_CAMERAS = 'FETCH_CAMERAS';
export const ADD_CAMERA = 'ADD_CAMERA';
export const DELETE_CAMERA = 'DELETE_CAMERA';
export const DELETE_CAMERAS = 'DELETE_CAMERAS';

// camera angles
export const FETCH_CAMERA_ANGLES = 'FETCH_CAMERA_ANGLES';
export const ADD_CAMERA_ANGLE = 'ADD_CAMERA_ANGLE';
export const DELETE_CAMERA_ANGLE = 'DELETE_CAMERA_ANGLE';
export const DELETE_CAMERA_ANGLES = 'DELETE_CAMERA_ANGLES';

// navigations
export const NAV_LINKS = {
    NAV_HOME: 'NAV_HOME',
    NAV_TYPICAL_CHILD: 'NAV_TYPICAL_CHILD',
    NAV_ATPICAL_CHILD: 'NAV_ATPICAL_CHILD',
    NAV_CAMERAS: 'NAV_CAMERASE',
    NAV_CAMERA_ANGLES: 'NAV_CAMERA_ANGLESE'
}
export const SET_NAV = 'SET_NAV';
